on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      -   name:   Checkout code
          uses:   actions/checkout@v3
      -   name:   Login to Docker Hub
          uses:   docker/login-action@v1
          with:
              username: ${{secrets.DOCKER_MAIL}}
              password: ${{ secrets.DOCKER_PASSWD }}
      -   name: Push dockerhub
          uses: mr-smithers-excellent/docker-build-push@v5
          with:
            image: seaman69/3dspace
            tags: visualizador-vehiculos
            registry: docker.io
            username: ${{secrets.DOCKER_MAIL}}
            password: ${{ secrets.DOCKER_PASSWD }}
